// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe_FibfHiJzUb2swAlStyRgy9_BfH-yYo',
    appId: '1:184407385618:web:4f2377989264db4baedacb',
    messagingSenderId: '184407385618',
    projectId: 'mamanike-d4d52',
    authDomain: 'mamanike-d4d52.firebaseapp.com',
    databaseURL: 'https://mamanike-d4d52-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mamanike-d4d52.appspot.com',
    measurementId: 'G-E060T7X18J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa2npH9Lm0XBYKqV5l6s6GxuiLYJ_ZZPk',
    appId: '1:184407385618:android:c2a88a7835033109aedacb',
    messagingSenderId: '184407385618',
    projectId: 'mamanike-d4d52',
    databaseURL: 'https://mamanike-d4d52-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mamanike-d4d52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANBbrfX_hBaJOiBrlcYDgGnmI3JUuZcOs',
    appId: '1:184407385618:ios:59575765087076b8aedacb',
    messagingSenderId: '184407385618',
    projectId: 'mamanike-d4d52',
    databaseURL: 'https://mamanike-d4d52-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mamanike-d4d52.appspot.com',
    iosBundleId: 'com.app.mamanike.mamanike',
  );
}
